title: michael setteducati
author:
  name: Michael Setteducati
  email: michael.setteducati@gmail.com
description: >-
  My personal website!

domain: msetteducati.github.io
baseurl: ""
url: https://msetteducati.github.io

minima:
  date_format: "%b %-d, %Y"
  social_links:
    github: msetteducati
    linkedin: michaelsetteducati
    # - { platform: github,  user_url: "https://github.com/msetteducati" }
    # - { platform: linkedin, user_url: "linkedin.com/in/michaelsetteducati" }

# Config
header_pages:
  - resume.md
  - research.md

# Build settings
plugins:
  - jekyll-feed
  - jekyll-remote-theme
remote_theme: jekyll/minima@6966444
sass:
  sass_dir: assets/css
  style: compressed