title: Michael Setteducati
email: michael.setteducati.setteducati
description: >-
  My personal website!
domain: msetteducati.github.io
baseurl: ""
url: https://msetteducati.github.io
github_username:  msetteducati

# Build settings
theme: minima
#theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

# Config
header_pages:
  - resume.md
  - research.md